[package]
name = "fractal"
version = "0.2.0"
edition = "2024"
description = "A CLI for exploring and editing SAP S/4HANA development systems"
license = "MIT"
authors = ["Tristan Russell <tristan.russell@iss-i.ca>"]
repository = "https://github.com/tristanrussell2000/fractal-cli"

[package.metadata.wix]
upgrade-guid = "C542D074-61DD-43FB-A1B9-B0C297DCBADF"
path-guid = "3ACAF9F9-AA1C-4647-B8DB-25445FBF5E2F"
license = false
eula = false

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
directories = "6"
thiserror = "2"
keyring = "4"
keyring-core = "1"
rpassword = "7"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.13.4", default-features = false, features = ["rustls", "cookies"] }
url = "2.5.8"
roxmltree = "0.21.1"
futures = "0.3"
regex = "1"
sha2 = "0.10"

[dev-dependencies]
wiremock = "0.6.5"

[profile.release]
lto = true
codegen-units = 1
strip = true

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
